name: Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/pacman@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update pacman contribution graph" || exit 0
          git push
